#version: '3.8'

services:
  api:
    image: my_api
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    container_name: db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    ports:
      - "1001:5432"

volumes:
  postgres_data: